app:
  debug: false
  capture: false
  width: 600.0
  clear_bg: kCt
  bg_alpha: 0.2 # low enough so it won't clear for gpu
  time:
    realtime: true
    fps: 40.0
    bpm: 120.0
  midi: true
  audio: true
  redraw: 1.0
  svg:
    size: 120.0
    save: kAt
  ctx: |
    true;

drawing:
  sequencer:
    type: Square  # Rect, Hex
    rows: 5
    cols: 5
    size: 10
  ctx: |
    something = 10.0;
  node:
    val: x + something * a
    curve:
      closed: true
      start:
        type: Basic  # Reference
        loc: [0.0, 0.0]
        angle_pi: 0.0
      dirs:
        - type: Line
          length: 50.0
        - type: Angle
          angle_pi: 0.5
        - type: Arc
          arc_length: 0.5
          radius: 50.0