name: murrelet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: wasm32-unknown-unknown

    - name: Install alsa dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
    - name: cargo fmt
      run: cargo fmt -- --check
    - name: cargo check
      run: cargo check --verbose
    - name: cargo check (wasm)
      run: cargo check --verbose --target wasm32-unknown-unknown
    - name: cargo test
      run: cargo test --verbose



